In [ ]:
import pandas as pd
import pycountry

In [ ]:
countries = pd.read_csv('https://gist.githubusercontent.com/tadast/8827699/raw/f5cac3d42d16b78348610fc4ec301e9234f82821/countries_codes_and_coordinates.csv',sep = ',')

Encuentro una tabla con los codigos de los paises

In [ ]:
countries = countries[['Alpha-2 code','Alpha-3 code']]

In [ ]:
countries.to_csv('countries.csv',index = False)

In [ ]:
table = pd.read_csv('/Users/admin/Downloads/table2.csv') #Cargo todos los paises, sin los codigos de pais

In [ ]:
countries

    Alpha-2 code Alpha-3 code
0           "AF"        "AFG"
1           "AL"        "ALB"
2           "DZ"        "DZA"
3           "AS"        "ASM"
4           "AD"        "AND"
..           ...          ...
251         "WF"        "WLF"
252         "EH"        "ESH"
253         "YE"        "YEM"
254         "ZM"        "ZMB"
255         "ZW"        "ZWE"

[256 rows x 2 columns]

Matcheo los dos codigos y los intento implementar a la tabla csv

In [ ]:
countries['Alpha-2 code'] = countries['Alpha-2 code'].str.replace('"','')
countries['Alpha-3 code'] = countries['Alpha-3 code'].str.replace('"','')

In [ ]:
table['country_code_2'] = countries['Alpha-2 code']

Nos damos cuenta de que el proceso no es eficiente y optamos por usar una libreria para que pasandole como input los nombres de los paises, nos matchee los codigos de dos y tres digitos

In [ ]:
input_countries = list(table['name'])
countries = {}
for country in pycountry.countries:
    countries[country.name] = country.alpha_3

codes = [countries.get(country, 'NaN') for country in input_countries]

In [ ]:
codes

['AFG',
 'ALB',
 'DEU',
 'DZA',
 'AND',
 'AGO',
 'AIA',
 'ATA',
 'ATG',
 'NaN',
 'SAU',
 'ARG',
 'ARM',
 'ABW',
 'AUS',
 'AUT',
 'AZE',
 'BEL',
 'BHS',
 'BHR',
 'BGD',
 'BRB',
 'BLZ',
 'BEN',
 'BTN',
 'BLR',
 'MMR',
 'NaN',
 'NaN',
 'BWA',
 'BRA',
 'NaN',
 'BGR',
 'BFA',
 'BDI',
 'NaN',
 'KHM',
 'CMR',
 'CAN',
 'TCD',
 'CHL',
 'CHN',
 'CYP',
 'NaN',
 'COL',
 'COM',
 'COG',
 'COG',
 'NaN',
 'NaN',
 'NaN',
 'CRI',
 'HRV',
 'CUB',
 'DNK',
 'DMA',
 'ECU',
 'EGY',
 'SLV',
 'ARE',
 'ERI',
 'SVK',
 'SVN',
 'ESP',
 'NaN',
 'EST',
 'ETH',
 'PHL',
 'FIN',
 'FJI',
 'FRA',
 'GAB',
 'GMB',
 'GEO',
 'GHA',
 'GIB',
 'GRD',
 'GRC',
 'GRL',
 'GLP',
 'GUM',
 'GTM',
 'GUF',
 'GGY',
 'GIN',
 'GNQ',
 'GNB',
 'GUY',
 'HTI',
 'HND',
 'HKG',
 'HUN',
 'IND',
 'IDN',
 'NaN',
 'IRQ',
 'IRL',
 'BVT',
 'IMN',
 'CXR',
 'NFK',
 'ISL',
 'NaN',
 'CYM',
 'CCK',
 'COK',
 'ALA',
 'FRO',
 'SGS',
 'HMD',
 'MDV',
 'FLK',
 'MNP',
 'MHL',
 'NaN',
 'SLB',
 'TCA',
 'UMI',
 'NaN',
 'NaN',
 'ISR',
 'ITA',
 'JAM',
 'JPN',
 'JEY',
 'JOR',
 'KAZ',
 'KEN',
 'KGZ',
 'KIR',
 'KWT',
 'LBN',
 'NaN',
 'LSO',
 'LVA',
 'LBR',
 'LBY',
 'LIE',
 'LTU',
 'LUX',
 'MEX',
 'MCO',
 'MAC',
 'NaN',
 'MDG',
 'MYS',
 'MWI',
 'MLI',
 'MLT',
 'MAR',
 'MTQ',
 'MUS',
 'MRT',
 'MYT',
 'NaN',
 'NaN',
 'MNG',
 'MNE',
 'MSR',
 'MOZ',
 'NAM',
 'NRU',
 'NPL',
 'NIC',
 'NER',
 'NGA',
 'NIU',
 'NOR',
 'NCL',
 'NZL',
 'OMN',
 'NLD',
 'PAK',
 'PLW',
 'NaN',
 'PAN',
 'PNG',
 'PRY',
 'PER',
 'PYF',
 'POL',
 'PRT',
 'PRI',
 'QAT',
 'GBR',
 'CAF',
 'NaN',
 'DOM',
 'REU',
 'RWA',
 'ROU',
 'NaN',
 'ESH',
 'WSM',
 'ASM',
 'BLM',
 'KNA',
 'SMR',
 'MAF',
 'SPM',
 'VCT',
 'NaN',
 'LCA',
 'STP',
 'SEN',
 'SRB',
 'SYC',
 'SLE',
 'SGP',
 'NaN',
 'SOM',
 'LKA',
 'ZAF',
 'SDN',
 'SWE',
 'CHE',
 'SUR',
 'SJM',
 'NaN',
 'TJK',
 'THA',
 'NaN',
 'NaN',
 'IOT',
 'ATF',
 'NaN',
 'TGO',
 'TKL',
 'TON',
 'TTO',
 'TUN',
 'TKM',
 'TUR',
 'TUV',
 'UKR',
 'UGA',
 'URY',
 'UZB',
 'VUT',
 'NaN',
 'NaN',
 'WLF',
 'YEM',
 'DJI',
 'ZMB',
 'ZWE']

In [ ]:
table['country_code'] = codes

In [ ]:
table.to_csv('table.csv',index = False)

In [ ]:
table.to_csv('table3.csv',index = False)

In [ ]:
table

     country_id country_code               name continent country_code_2
0          2000          AFG        Afghanistan        AS             AF
1          2001          ALB            Albania        EU             AL
2          2002          DEU            Germany        EU             DZ
3          2003          DZA            Algeria        AF             AS
4          2004          AND            Andorra        EU             AD
..          ...          ...                ...       ...            ...
241        2241          WLF  Wallis and Futuna        OC             UM
242        2242          YEM              Yemen        AS             UY
243        2243          DJI           Djibouti        AF             UZ
244        2244          ZMB             Zambia        AF             VU
245        2245          ZWE           Zimbabwe        AF             VE

[246 rows x 5 columns]

Tabla final con dos y tres digitos